### ISSUE TITLE
panic: reached unreachable code

### ISSUE THREAD

**Issue by ca1e** [svercl/zshim#3]
zig version
0.11.0-dev.2368+f4b411314

```
D:\AppData\scoop\apps\zig-dev\current\lib\std\fs.zig:1798:37: 0x7ff6e4cbe314 in openDirAccessMaskW (shim.exe.obj)
            .OBJECT_NAME_INVALID => unreachable,
                                    ^
D:\AppData\scoop\apps\zig-dev\current\lib\std\fs.zig:1737:70: 0x7ff6e4caac0c in openDirW (shim.exe.obj)
        var dir = try self.openDirAccessMaskW(sub_path_w, flags, args.no_follow);
                                                                     ^
D:\AppData\scoop\apps\zig-dev\current\lib\std\child_process.zig:968:52: 0x7ff6e4ca830d in windowsCreateProcessPathExt (shim.exe.obj)
        break :dir std.fs.cwd().openDirW(dir_path_z.ptr, .{}, true) catch return error.FileNotFound;
                                                   ^
D:\AppData\scoop\apps\zig-dev\current\lib\std\child_process.zig:836:96: 0x7ff6e4c89a54 in spawnWindows (shim.exe.obj)
            windowsCreateProcessPathExt(self.allocator, &dir_buf, &app_buf, PATHEXT, cmd_line_w.ptr, envp_ptr, cwd_w_ptr, &siStartInfo, &piProcInfo) catch |no_path_err| {
                                                                                               ^
D:\AppData\scoop\apps\zig-dev\current\lib\std\child_process.zig:201:37: 0x7ff6e4c4cbae in spawn (shim.exe.obj)
            return self.spawnWindows();
                                    ^
D:\AppData\scoop\apps\zig-dev\current\lib\std\child_process.zig:208:23: 0x7ff6e4c45bb8 in spawnAndWait (shim.exe.obj)
        try self.spawn();
                      ^
D:\github\zshim\src\main.zig:105:31: 0x7ff6e4c451aa in main (shim.exe.obj)
    _ = try child.spawnAndWait();
                              ^
D:\AppData\scoop\apps\zig-dev\current\lib\std\start.zig:518:80: 0x7ff6e4c45f40 in main (shim.exe.obj)
    return @call(.always_inline, callMainWithArgs, .{ @intCast(usize, c_argc), @ptrCast([*][*:0]u8, c_argv), envp });
```

sorry my zig is poor, seems like it is some FileNotFound error?

**Comment by svercl** [comment]
When does this happen? During build, running a shim, or ...?

**Comment by svercl** [comment]
I know something similar happens when building on windows (or at least it used to)

**Comment by ca1e** [comment]
> When does this happen? During build, running a shim, or ...?

There are  some issues during build on Windows, but its still generate a exe there.This error occured when running as a shim.

Maybe the zig version broken some features?

**Comment by svercl** [comment]
Are you able to share the shim file that fails?

**Comment by ca1e** [comment]
during build on windows(zig build -Doptimize=ReleaseSafe):
```
install shim: error: unable to update file from 'D:\github\zshim\zig-cache\o\9e9d4110f5767a4796dc653c3d4d5415\shim.pdb' to 'D:\github\zshim\zig-out\bin\shim.pdb': FileNotFound
Build Summary: 1/3 steps succeeded; 1 failed (disable with -fno-summary)
install transitive failure
+- install shim failure
   +- zig build-exe shim ReleaseSafe native success 9s MaxRSS:100M
error: the following build command failed with exit code 1:
D:\github\zshim\zig-cache\o\a3e11b1fddf06008c7b0c314c0c5d9ea\build.exe D:\AppData\scoop\apps\zig-dev\current\zig.exe D:\github\zshim D:\github\zshim\zig-cache C:\XXX\AppData\Local\zig -Doptimize=ReleaseSafe
```

generated exe(delete '.zip'):[shim.exe.zip](https://github.com/svercl/zshim/files/11165657/shim.exe.zip)


by replace the existed shim file and run it:
```
panic: reached unreachable code
Unable to dump stack trace: debug info stripped
```

debug build(zig build -Doptimize=Debug):[shimDebug.exe.zip](https://github.com/svercl/zshim/files/11165707/shimDebug.exe.zip)

during running error:see above

**Comment by svercl** [comment]
Oh I see, so this is happening when trying to run it like `zig build run`? I think the first is related to trying to `zig build install` which is technically unsupported, and will be removed.

Is this running with any `.shim` file? (not the exe itself)

**Comment by svercl** [comment]
I noticed an issue with the way I was handling the shim files. Please let me know if this works for you.

**Comment by svercl** [comment]
I haven't had as much time as I'd like to look into this further. I'm hoping to in the next few days. It is strange that it is reaching unreachable code in the standard library, which shouldn't be happening.

**Comment by svercl** [comment]
The shim format has changed since I worked on this. I have just pushed a fix.

**Comment by ca1e** [comment]
oh you are right, the correct separator fixed the problem, my bad for not clearly show the shimfile content :(
